%
% Author: Rongqing Chen
% Date: 29-Apr-2020
%
% Script overview: 
% This script reads the voltage/potential measurements from the '.get' file
% generated by Draeger EIT Data Analysis Tool. The function outputs data as
% '208*frames' structure, which can be used directly for image
% reconstruction.
% Warning: You need EIDORS toolbox for this function!
%

function voltReorder = read_getData(patientDataPath)

voltages = eidors_readdata(patientDataPath,'get');

voltReorder = [];
for i=1:16
    
    temp = voltages(i*16-15:i*16,:);
    
    if i==16
        temp(1,:) = [];
        temp(14:15,:) = [];
    else
        temp = [temp; temp(1:i+1,:)];
        temp(1:1+i,:) = [];
        temp(14:16,:) = [];
    end
    
    voltReorder = [voltReorder; temp];
end
