% Copyright 2019 Province of British Columbia
% 
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
% 
%    http://www.apache.org/licenses/LICENSE-2.0
% 
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
%
% Author: Rongqing Chen
% Date: 29-Apr-2020
%
% Script overview: 
% This script reads the voltage/potential measurements from the '.get' file
% generated by Draeger EIT Data Analysis Tool. The function outputs data as
% '208*frames' structure, which can be used directly for image
% reconstruction.
% Warning: You need EIDORS toolbox for this function!
%

function voltReorder = read_getData(patientDataPath)

voltages = eidors_readdata(patientDataPath,'get');

voltReorder = [];
for i=1:16
    
    temp = voltages(i*16-15:i*16,:);
    
    if i==16
        temp(1,:) = [];
        temp(14:15,:) = [];
    else
        temp = [temp; temp(1:i+1,:)];
        temp(1:1+i,:) = [];
        temp(14:16,:) = [];
    end
    
    voltReorder = [voltReorder; temp];
end
